using System.Net;
using System.Net.Http.Headers;
using System.Net.Http.Json;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using RashePharma.Application.DTOs.Auth;
using RashePharma.Application.DTOs.Orders;
using RashePharma.Domain.Entities;
using RashePharma.Infrastructure.Data;
using RashePharma.Tests.Infrastructure;
using Xunit;

namespace RashePharma.Tests.Controllers;

public class OrdersControllerTests : IClassFixture<CustomWebApplicationFactory>
{
    private readonly CustomWebApplicationFactory _factory;
    private readonly HttpClient _client;

    public OrdersControllerTests(CustomWebApplicationFactory factory)
    {
        _factory = factory;
        _client = factory.CreateClient();
    }


    // =========================================================
    // AUTHENTICATED USER
    // =========================================================

    private async Task<(int UserId, string Token)> CreateAuthenticatedUserAsync()
    {
        await SeedRoleAsync();

        var email =
            $"order-auth-{Guid.NewGuid():N}@example.com";

        var registerDto = new RegisterDto
        {
            FirstName = "Order",
            LastName = "TestUser",
            Email = email,
            PhoneNumber = "+91-9876543210",
            Country = "India",
            Password = "password123"
        };

        var registerResponse = await _client.PostAsJsonAsync(
            "/api/auth/register",
            registerDto);

        Assert.Equal(
            HttpStatusCode.OK,
            registerResponse.StatusCode);

        var registerResult =
            await registerResponse.Content
                .ReadFromJsonAsync<AuthResponseDto>();

        Assert.NotNull(registerResult);
        Assert.True(registerResult.UserId > 0);


        // Login to get a fresh JWT.
        var loginDto = new LoginDto
        {
            Email = email,
            Password = "password123"
        };

        var loginResponse = await _client.PostAsJsonAsync(
            "/api/auth/login",
            loginDto);

        Assert.Equal(
            HttpStatusCode.OK,
            loginResponse.StatusCode);

        var loginResult =
            await loginResponse.Content
                .ReadFromJsonAsync<AuthResponseDto>();

        Assert.NotNull(loginResult);
        Assert.False(
            string.IsNullOrWhiteSpace(loginResult.Token));

        return (
            loginResult.UserId,
            loginResult.Token
        );
    }


    private void SetBearerToken(string token)
    {
        _client.DefaultRequestHeaders.Authorization =
            new AuthenticationHeaderValue(
                "Bearer",
                token);
    }


    private void ClearBearerToken()
    {
        _client.DefaultRequestHeaders.Authorization = null;
    }


    // =========================================================
    // ROLE
    // =========================================================

    private async Task SeedRoleAsync()
    {
        using var scope = _factory.Services.CreateScope();

        var db = scope.ServiceProvider
            .GetRequiredService<ApplicationDbContext>();

        if (!db.Roles.Any(r => r.Id == 2))
        {
            db.Roles.Add(new Role
            {
                Id = 2,
                Name = "Customer"
            });

            await db.SaveChangesAsync();
        }
    }


    private async Task<string> CreateAdminTokenAsync()
    {
        using var scope = _factory.Services.CreateScope();

        var db = scope.ServiceProvider
            .GetRequiredService<ApplicationDbContext>();


        // Make sure Admin role exists.
        var adminRole = await db.Roles
            .FirstOrDefaultAsync(r => r.Id == 1);

        if (adminRole == null)
        {
            adminRole = new Role
            {
                Id = 1,
                Name = "Admin"
            };

            db.Roles.Add(adminRole);

            await db.SaveChangesAsync();
        }


        var email =
            $"admin-{Guid.NewGuid():N}@example.com";

        var admin = new User
        {
            FirstName = "Test",
            LastName = "Admin",
            Email = email,
            PhoneNumber = "+91-9999999999",
            Country = "India",
            RoleId = adminRole.Id,
            IsActive = true
        };

        var passwordHasher = new PasswordHasher<User>();

        admin.PasswordHash =
            passwordHasher.HashPassword(
                admin,
                "adminPassword123");

        db.Users.Add(admin);

        await db.SaveChangesAsync();


        // Login through the real API so that the JWT is
        // generated by the actual JwtTokenService.
        var loginDto = new LoginDto
        {
            Email = email,
            Password = "adminPassword123"
        };

        var loginResponse = await _client.PostAsJsonAsync(
            "/api/auth/login",
            loginDto);

        Assert.Equal(
            HttpStatusCode.OK,
            loginResponse.StatusCode);

        var result =
            await loginResponse.Content
                .ReadFromJsonAsync<AuthResponseDto>();

        Assert.NotNull(result);
        Assert.False(
            string.IsNullOrWhiteSpace(result.Token));

        return result.Token;
    }


    // =========================================================
    // ADDRESS
    // =========================================================

    private async Task<int> CreateAddressAsync(int userId)
    {
        using var scope = _factory.Services.CreateScope();

        var db = scope.ServiceProvider
            .GetRequiredService<ApplicationDbContext>();

        var address = new Address
        {
            UserId = userId,
            AddressLine1 = "123 Order Street",
            AddressLine2 = "Test Area",
            City = "Bengaluru",
            State = "Karnataka",
            PostalCode = "560001",
            Country = "India",
            AddressType = "Shipping",
            IsDefault = true
        };

        db.Addresses.Add(address);

        await db.SaveChangesAsync();

        return address.Id;
    }


    // =========================================================
    // PRODUCT + VARIANT
    // =========================================================

    private async Task<int> CreateCategoryAsync()
    {
        using var scope = _factory.Services.CreateScope();

        var db = scope.ServiceProvider
            .GetRequiredService<ApplicationDbContext>();

        var category = new Category
        {
            Name = $"Order Category {Guid.NewGuid():N}",
            Slug = $"order-category-{Guid.NewGuid():N}",
            Description = "Category for order controller tests",
            IsActive = true
        };

        db.Categories.Add(category);

        await db.SaveChangesAsync();

        return category.Id;
    }


    private async Task<int> CreateProductAsync(int categoryId)
    {
        using var scope = _factory.Services.CreateScope();

        var db = scope.ServiceProvider
            .GetRequiredService<ApplicationDbContext>();

        var product = new Product
        {
            Name = $"Order Product {Guid.NewGuid():N}",
            Slug = $"order-product-{Guid.NewGuid():N}",
            GenericName = "Test Generic",
            Composition = "Test Composition",
            DosageForm = "Tablet",
            Description = "Product for order controller tests",
            Manufacturer = "Test Manufacturer",
            CategoryId = categoryId,
            IsActive = true
        };

        db.Products.Add(product);

        await db.SaveChangesAsync();

        return product.Id;
    }


    private async Task<int> CreateProductVariantAsync(int productId)
    {
        using var scope = _factory.Services.CreateScope();

        var db = scope.ServiceProvider
            .GetRequiredService<ApplicationDbContext>();

        var variant = new ProductVariant
        {
            ProductId = productId,
            Strength = "500 mg",
            PackSize = "10 Tablets",
            Price = 100m,
            SKU = $"ORDER-SKU-{Guid.NewGuid():N}",
            StockQuantity = 100,
            IsActive = true
        };

        db.ProductVariants.Add(variant);

        await db.SaveChangesAsync();

        return variant.Id;
    }


    // =========================================================
    // CART
    // =========================================================

    private async Task CreateCartItemAsync(
        int userId,
        int productVariantId,
        int quantity = 2,
        decimal unitPrice = 100m)
    {
        using var scope = _factory.Services.CreateScope();

        var db = scope.ServiceProvider
            .GetRequiredService<ApplicationDbContext>();

        var cart = new Cart
        {
            UserId = userId
        };

        db.Carts.Add(cart);

        await db.SaveChangesAsync();

        var cartItem = new CartItem
        {
            CartId = cart.Id,
            ProductVariantId = productVariantId,
            Quantity = quantity,
            UnitPrice = unitPrice
        };

        db.CartItems.Add(cartItem);

        await db.SaveChangesAsync();
    }


    // =========================================================
    // ORDER
    // =========================================================

    private async Task<int> CreateOrderAsync(
        int userId,
        int productVariantId,
        decimal unitPrice = 100m,
        int quantity = 2)
    {
        using var scope = _factory.Services.CreateScope();

        var db = scope.ServiceProvider
            .GetRequiredService<ApplicationDbContext>();

        var order = new Order
        {
            UserId = userId,
            OrderNumber = $"ORD-TEST-{Guid.NewGuid():N}",
            TotalAmount = unitPrice * quantity,
            Currency = "INR",
            Status = "Pending",

            ShippingAddressLine1 = "123 Order Street",
            ShippingAddressLine2 = "Test Area",
            ShippingCity = "Bengaluru",
            ShippingState = "Karnataka",
            ShippingPostalCode = "560001",
            ShippingCountry = "India"
        };

        var variant = await db.ProductVariants
            .Include(v => v.Product)
            .FirstAsync(v => v.Id == productVariantId);

        var orderItem = new OrderItem
        {
            OrderId = order.Id,
            ProductVariantId = productVariantId,
            ProductName = variant.Product.Name,
            Strength = variant.Strength,
            PackSize = variant.PackSize,
            Quantity = quantity,
            UnitPrice = unitPrice
        };

        order.Items.Add(orderItem);

        db.Orders.Add(order);

        await db.SaveChangesAsync();

        return order.Id;
    }


    private async Task<(
        int UserId,
        int AddressId,
        int VariantId,
        string Token)> CreateOrderSetupAsync()
    {
        var user = await CreateAuthenticatedUserAsync();

        var addressId =
            await CreateAddressAsync(user.UserId);

        var categoryId =
            await CreateCategoryAsync();

        var productId =
            await CreateProductAsync(categoryId);

        var variantId =
            await CreateProductVariantAsync(productId);

        return (
            user.UserId,
            addressId,
            variantId,
            user.Token
        );
    }


    // =========================================================
    // GET MY ORDERS
    // =========================================================

    [Fact]
    public async Task GetMyOrders_ShouldReturnOk_WhenUserHasOrders()
    {
        // Arrange
        var setup = await CreateOrderSetupAsync();

        await CreateOrderAsync(
            setup.UserId,
            setup.VariantId);

        SetBearerToken(setup.Token);

        // Act
        var response = await _client.GetAsync(
            "/api/orders/my-orders");

        // Assert
        Assert.Equal(
            HttpStatusCode.OK,
            response.StatusCode);

        var orders =
            await response.Content
                .ReadFromJsonAsync<List<OrderListDto>>();

        Assert.NotNull(orders);
        Assert.NotEmpty(orders);

        var order = Assert.Single(orders);

        Assert.True(order.Id > 0);
        Assert.Equal("INR", order.Currency);
        Assert.Equal("Pending", order.Status);
    }


    [Fact]
    public async Task GetMyOrders_ShouldReturnEmptyList_WhenUserHasNoOrders()
    {
        // Arrange
        var setup = await CreateOrderSetupAsync();

        SetBearerToken(setup.Token);

        // Act
        var response = await _client.GetAsync(
            "/api/orders/my-orders");

        // Assert
        Assert.Equal(
            HttpStatusCode.OK,
            response.StatusCode);

        var orders =
            await response.Content
                .ReadFromJsonAsync<List<OrderListDto>>();

        Assert.NotNull(orders);
        Assert.Empty(orders);
    }


    [Fact]
    public async Task GetMyOrders_ShouldReturnUnauthorized_WhenTokenIsMissing()
    {
        // Arrange
        ClearBearerToken();

        // Act
        var response = await _client.GetAsync(
            "/api/orders/my-orders");

        // Assert
        Assert.Equal(
            HttpStatusCode.Unauthorized,
            response.StatusCode);
    }


    // =========================================================
    // GET BY ID
    // =========================================================

    [Fact]
    public async Task GetById_ShouldReturnOk_WhenOrderBelongsToUser()
    {
        // Arrange
        var setup = await CreateOrderSetupAsync();

        var orderId = await CreateOrderAsync(
            setup.UserId,
            setup.VariantId);

        SetBearerToken(setup.Token);

        // Act
        var response = await _client.GetAsync(
            $"/api/orders/{orderId}");

        // Assert
        Assert.Equal(
            HttpStatusCode.OK,
            response.StatusCode);

        var order =
            await response.Content
                .ReadFromJsonAsync<OrderDetailsDto>();

        Assert.NotNull(order);
        Assert.Equal(orderId, order.Id);
        Assert.Equal("INR", order.Currency);
        Assert.Equal("Pending", order.Status);
        Assert.NotEmpty(order.Items);
    }


    [Fact]
    public async Task GetById_ShouldReturnNotFound_WhenOrderDoesNotBelongToUser()
    {
        // Arrange
        var setup = await CreateOrderSetupAsync();

        var anotherUser =
            await CreateAuthenticatedUserAsync();

        var orderId = await CreateOrderAsync(
            setup.UserId,
            setup.VariantId);

        // Login as another user.
        SetBearerToken(anotherUser.Token);

        // Act
        var response = await _client.GetAsync(
            $"/api/orders/{orderId}");

        // Assert
        Assert.Equal(
            HttpStatusCode.NotFound,
            response.StatusCode);
    }


    [Fact]
    public async Task GetById_ShouldReturnNotFound_WhenOrderDoesNotExist()
    {
        // Arrange
        var setup = await CreateOrderSetupAsync();

        SetBearerToken(setup.Token);

        const int orderId = 999999;

        // Act
        var response = await _client.GetAsync(
            $"/api/orders/{orderId}");

        // Assert
        Assert.Equal(
            HttpStatusCode.NotFound,
            response.StatusCode);
    }


    // =========================================================
    // GET BY ORDER NUMBER
    // =========================================================

    [Fact]
    public async Task GetByOrderNumber_ShouldReturnOk_WhenOrderBelongsToUser()
    {
        // Arrange
        var setup = await CreateOrderSetupAsync();

        var orderId = await CreateOrderAsync(
            setup.UserId,
            setup.VariantId);

        using var scope = _factory.Services.CreateScope();

        var db = scope.ServiceProvider
            .GetRequiredService<ApplicationDbContext>();

        var order = await db.Orders.FindAsync(orderId);

        Assert.NotNull(order);

        SetBearerToken(setup.Token);

        // Act
        var response = await _client.GetAsync(
            $"/api/orders/number/{order!.OrderNumber}");

        // Assert
        Assert.Equal(
            HttpStatusCode.OK,
            response.StatusCode);

        var result =
            await response.Content
                .ReadFromJsonAsync<OrderDetailsDto>();

        Assert.NotNull(result);
        Assert.Equal(orderId, result.Id);
        Assert.Equal(order.OrderNumber, result.OrderNumber);
    }


    [Fact]
    public async Task GetByOrderNumber_ShouldReturnNotFound_WhenOrderDoesNotBelongToUser()
    {
        // Arrange
        var setup = await CreateOrderSetupAsync();

        var anotherUser =
            await CreateAuthenticatedUserAsync();

        var orderId = await CreateOrderAsync(
            setup.UserId,
            setup.VariantId);

        using var scope = _factory.Services.CreateScope();

        var db = scope.ServiceProvider
            .GetRequiredService<ApplicationDbContext>();

        var order = await db.Orders.FindAsync(orderId);

        Assert.NotNull(order);

        // Authenticate as another user.
        SetBearerToken(anotherUser.Token);

        // Act
        var response = await _client.GetAsync(
            $"/api/orders/number/{order!.OrderNumber}");

        // Assert
        Assert.Equal(
            HttpStatusCode.NotFound,
            response.StatusCode);
    }


    [Fact]
    public async Task GetByOrderNumber_ShouldReturnNotFound_WhenOrderDoesNotExist()
    {
        // Arrange
        var setup = await CreateOrderSetupAsync();

        SetBearerToken(setup.Token);

        const string orderNumber =
            "ORD-DOES-NOT-EXIST";

        // Act
        var response = await _client.GetAsync(
            $"/api/orders/number/{orderNumber}");

        // Assert
        Assert.Equal(
            HttpStatusCode.NotFound,
            response.StatusCode);
    }


    // =========================================================
    // CREATE ORDER
    // =========================================================

    [Fact]
    public async Task Create_ShouldReturnOk_WhenCartAndAddressAreValid()
    {
        // Arrange
        var setup = await CreateOrderSetupAsync();

        await CreateCartItemAsync(
            setup.UserId,
            setup.VariantId,
            quantity: 2,
            unitPrice: 100m);

        var dto = new CreateOrderDto
        {
            AddressId = setup.AddressId
        };

        SetBearerToken(setup.Token);

        // Act
        var response = await _client.PostAsJsonAsync(
            "/api/orders",
            dto);

        // Assert
        Assert.Equal(
            HttpStatusCode.OK,
            response.StatusCode);

        var order =
            await response.Content
                .ReadFromJsonAsync<OrderDetailsDto>();

        Assert.NotNull(order);

        Assert.True(order.Id > 0);
        Assert.False(
            string.IsNullOrWhiteSpace(order.OrderNumber));

        Assert.StartsWith(
            "ORD-",
            order.OrderNumber);

        Assert.Equal("INR", order.Currency);
        Assert.Equal("Pending", order.Status);

        Assert.Equal(
            200m,
            order.TotalAmount);

        Assert.Equal(
            "123 Order Street",
            order.ShippingAddressLine1);

        Assert.Equal(
            "Bengaluru",
            order.ShippingCity);

        Assert.Equal(
            "Karnataka",
            order.ShippingState);

        var item = Assert.Single(order.Items);

        Assert.Equal(
            setup.VariantId,
            item.ProductVariantId);

        Assert.Equal(
            2,
            item.Quantity);

        Assert.Equal(
            100m,
            item.UnitPrice);
    }


    [Fact]
    public async Task Create_ShouldReturnBadRequest_WhenCartIsEmpty()
    {
        // Arrange
        var setup = await CreateOrderSetupAsync();

        var dto = new CreateOrderDto
        {
            AddressId = setup.AddressId
        };

        SetBearerToken(setup.Token);

        // Act
        var response = await _client.PostAsJsonAsync(
            "/api/orders",
            dto);

        // Assert
        Assert.Equal(
            HttpStatusCode.BadRequest,
            response.StatusCode);
    }


    [Fact]
    public async Task Create_ShouldReturnBadRequest_WhenAddressBelongsToAnotherUser()
    {
        // Arrange
        var setup = await CreateOrderSetupAsync();

        var anotherUser =
            await CreateAuthenticatedUserAsync();

        var anotherUserAddressId =
            await CreateAddressAsync(
                anotherUser.UserId);

        await CreateCartItemAsync(
            setup.UserId,
            setup.VariantId,
            quantity: 1,
            unitPrice: 100m);

        var dto = new CreateOrderDto
        {
            AddressId = anotherUserAddressId
        };

        // Authenticate as original user.
        SetBearerToken(setup.Token);

        // Act
        var response = await _client.PostAsJsonAsync(
            "/api/orders",
            dto);

        // Assert
        Assert.Equal(
            HttpStatusCode.BadRequest,
            response.StatusCode);
    }


    [Fact]
    public async Task Create_ShouldReturnUnauthorized_WhenTokenIsMissing()
    {
        // Arrange
        ClearBearerToken();

        var dto = new CreateOrderDto
        {
            AddressId = 1
        };

        // Act
        var response = await _client.PostAsJsonAsync(
            "/api/orders",
            dto);

        // Assert
        Assert.Equal(
            HttpStatusCode.Unauthorized,
            response.StatusCode);
    }


    // =========================================================
    // UPDATE STATUS
    // =========================================================

    [Fact]
    public async Task UpdateStatus_ShouldReturnNoContent_WhenOrderExists()
    {
        // Arrange
        var setup = await CreateOrderSetupAsync();

        var orderId = await CreateOrderAsync(
            setup.UserId,
            setup.VariantId);

        var adminToken =
            await CreateAdminTokenAsync();

        SetBearerToken(adminToken);

        var dto = new UpdateOrderStatusDto
        {
            Status = "Confirmed",
            Comment = "Order confirmed successfully."
        };

        // Act
        var response = await _client.PatchAsJsonAsync(
            $"/api/orders/{orderId}/status",
            dto);

        // Assert
        Assert.Equal(
            HttpStatusCode.NoContent,
            response.StatusCode);
    }


    [Fact]
    public async Task UpdateStatus_ShouldReturnNotFound_WhenOrderDoesNotExist()
    {
        // Arrange
        var adminToken =
            await CreateAdminTokenAsync();

        SetBearerToken(adminToken);

        const int orderId = 999999;

        var dto = new UpdateOrderStatusDto
        {
            Status = "Confirmed",
            Comment = "Test status update."
        };

        // Act
        var response = await _client.PatchAsJsonAsync(
            $"/api/orders/{orderId}/status",
            dto);

        // Assert
        Assert.Equal(
            HttpStatusCode.NotFound,
            response.StatusCode);
    }


    [Fact]
    public async Task UpdateStatus_ShouldReturnForbidden_WhenUserIsNotAdmin()
    {
        // Arrange
        var setup = await CreateOrderSetupAsync();

        var orderId = await CreateOrderAsync(
            setup.UserId,
            setup.VariantId);

        // Customer token.
        SetBearerToken(setup.Token);

        var dto = new UpdateOrderStatusDto
        {
            Status = "Confirmed",
            Comment = "Customer should not update status."
        };

        // Act
        var response = await _client.PatchAsJsonAsync(
            $"/api/orders/{orderId}/status",
            dto);

        // Assert
        Assert.Equal(
            HttpStatusCode.Forbidden,
            response.StatusCode);
    }
}